
/*
	제목 : 한라그룹 실적 관리시스템 테이블 스키마
	작성 : 2018.07.20
	내용 : 시스템에 필요한 스키마 및 기초 데이터를 설정해둡니다.
*/

/*
	관리자 관리 관련 디비 테이블
*/

-- 관리자관리 > 접속로그(개발)
CREATE TABLE ADMIN_ACCESS_LOG
(
	ACCESS_DATE				DATETIME NOT NULL,
	USER_KEY				VARCHAR(11) NOT NULL,
	EMP_NO					VARCHAR(16) NOT NULL,
	USER_KOR_NAME			NVARCHAR(64) NULL,
	IP						VARCHAR(64) NULL,
	MEMO					NVARCHAR(256) NULL,
	DESCRITION				NVARCHAR(1024) NULL,
	PRIMARY KEY( ACCESS_DATE, USER_KEY)
);

-- 관리자관리 > 조직관리 : 미사용
/*
CREATE TABLE ORG_MNG
(
	SEQ						INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	ORG_NAME				NVARCHAR(64) NOT NULL,
	ORG_LEVEL				INT NOT NULL,
	ORG_ORD					INT NOT NULL DEFAULT(0),
	PARENTN_SEQ				INT NOT NULL DEFAULT(0),
	IS_USE					CHAR(1) NULL DEFAULT(N'Y'),

	USER_KEY				VARCHAR(11) NOT NULL,
	EMP_NO					VARCHAR(16) NULL,
	CREATE_DATE				DATETIME NULL
);
*/

-- 관리자관리 > 조직관리 - 부문정보(개발)
CREATE TABLE ORG_UNION
(
	SEQ						INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	UNION_NAME				NVARCHAR(64) NOT NULL,
	IS_USE					CHAR(1) NULL DEFAULT(N'Y'),

	USER_KEY				VARCHAR(11) NOT NULL,
	EMP_NO					VARCHAR(16) NULL,
	CREATE_DATE				DATETIME NULL
);

-- 관리자관리 > 조직관리 - 회사정보(개발)
CREATE TABLE ORG_COMPANY
(
	ORG_UNION_SEQ			INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	COMPANY_NAME			NVARCHAR(64) NOT NULL,
	IS_USE					CHAR(1) NULL DEFAULT(N'Y'),

	USER_KEY				VARCHAR(11) NOT NULL,
	EMP_NO					VARCHAR(16) NULL,
	CREATE_DATE				DATETIME NULL
);

-- 관리자관리 > 조직관리 - Buniess Unit 정보(개발)
CREATE TABLE ORG_BUSINESS
(
	ORG_COMPANY_SEQ			INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	BUSINESS_NAME			NVARCHAR(64) NOT NULL,
	IS_USE					CHAR(1) NULL DEFAULT(N'Y'),

	USER_KEY				VARCHAR(11) NOT NULL,
	EMP_NO					VARCHAR(16) NULL,
	CREATE_DATE				DATETIME NULL
);

-- 관리자관리 > 관리자 권한관리
CREATE TABLE ADMIN_AUTH
(
	AUTH_USER_KEY			VARCHAR(11) NOT NULL PRIMARY KEY,
	AUTH_EMP_NO				VARCHAR(16) NOT NULL,
	USER_KOR_NAME			NVARCHAR(64) NULL,
	AUTH_LEVEL				INT NOT NULL,
	IS_USE					CHAR(1) NULL DEFAULT(N'Y'),

	USER_KEY				VARCHAR(11) NOT NULL,
	EMP_NO					VARCHAR(16) NULL,
	CREATE_DATE				DATETIME NULL
);
-- 관리자관리 > 관리자 권한관리 - 조직권한
CREATE TABLE ADMIN_ORG_AUTH
(
	AUTH_USER_KEY			VARCHAR(11) NOT NULL,
	ORG_COMPANY_SEQ			INT NOT NULL,
	PRIMARY KEY (AUTH_USER_KEY, ORG_COMPANY_SEQ)
);

-- 관리자관리 > 보고시스템 권한관리
CREATE TABLE SYSTEM_AUTH
(
	AUTH_USER_KEY			VARCHAR(11) NOT NULL PRIMARY KEY,
	AUTH_EMP_NO				VARCHAR(16) NOT NULL,
	USER_KOR_NAME			NVARCHAR(64) NULL,
	IS_USE					CHAR(1) NULL DEFAULT(N'Y'),

	USER_KEY				VARCHAR(11) NOT NULL,
	EMP_NO					VARCHAR(16) NULL,
	CREATE_DATE				DATETIME NULL
);
-- 관리자권한 > 보고시스템 권한관리 - 조직권한
CREATE TABLE SYSTEM_ORG_AUTH
(
	AUTH_USER_KEY			VARCHAR(11) NOT NULL,
	ORG_COMPANY_SEQ			INT NOT NULL,
	PRIMARY KEY (AUTH_USER_KEY, ORG_COMPANY_SEQ)
);
-- 관리자권한 > 보고시스템 권한관리 - 메뉴권한
CREATE TABLE SYSTEM_MENU_AUTH
(
	AUTH_USER_KEY			VARCHAR(11) NOT NULL,
	MENU_TYPE				INT NOT NULL,
	PRIMARY KEY (AUTH_USER_KEY, MENU_TYPE)
);

/*
	일정 관리 관련 디비 테이블
*/

-- 일정관리 > 등록일정계획 : APPLY_CHK : 승인요청 상태 [Y - 승인요청, N - 미승인]
-- 설명 : APPLY_CHK가 Y가 되면 더 이상 계획일정은 수정이 안되는 것인지?
CREATE TABLE PLAN_SCHEDULE
(
	SCHEDULE_YEAR		CHAR(4) NOT NULL PRIMARY KEY,
	PLAN_DT_START		DATE NOT NULL,
	PLAN_DT_END			DATE NOT NULL,
	APPLY_CHK			CHAR(1) NOT NULL DEFAULT(N'N'),

	USER_KEY			VARCHAR(11) NOT NULL,
	EMP_NO				VARCHAR(16) NULL,
	CREATE_DATE			DATETIME NULL
);
-- 일정관리 > 등록일정계획 - 실적등록
CREATE TABLE PLAN_SCHEDULE_PERFORMANCE_REG
(
	SCHEDULE_YEAR		CHAR(4) NOT NULL,
	REG_MONTH			CHAR(2) NOT NULL,

	REG_DT_START		DATE NOT NULL,
	REG_DT_END			DATE NOT NULL,

	PRIMARY KEY (SCHEDULE_YEAR, REG_MONTH)
);

/*
	사업계획 관련 디비 테이블
*/

-- 사업계획 > 손익월별계획
CREATE TABLE PLAN_MONTHLY_PAL
(
	SEQ					INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	MONTHLY_PAL_YEAR	CHAR(4) NOT NULL,
	ORG_COMPANY_SEQ		INT NOT NULL,

	REGIST_STATUS		INT NOT NULL,
	-- 요약 코멘트 빠질수 있음. 안 빠진다고 하여도 여기서 관리는 힘듬
	--SUMMARY_COMMENT		NVARCHAR(MAX) NULL,

	USER_KEY			VARCHAR(11) NOT NULL,
	EMP_NO				VARCHAR(16) NULL,
	CREATE_DATE			DATETIME NULL
);

-- 사업계획 > 손익월별계획 - 부서데이터
CREATE TABLE PLAN_MONTHLY_PAL_BUSINESS
(
	PLAN_MONTHLY_PAL_SEQ	INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),
		
	ORG_BUSINESS_SEQ		INT NULL,
	MONTHLY					VARCHAR(4) NULL,

	SALES					DECIMAL(12, 2) NOT NULL,
	EBIT					DECIMAL(12, 2) NOT NULL,
	EBIT_RATE			DECIMAL(12, 2) NULL,
	PBT						DECIMAL(12, 2) NOT NULL,

	PRIMARY KEY ( PLAN_MONTHLY_PAL_SEQ, SEQ)
);

-- 사업계획 > 손익월별계획 -  부서(월) 합계
CREATE TABLE PLAN_MONTHLY_PAL_BUSINESS_MONTHLY_SUM
(
	PLAN_MONTHLY_PAL_SEQ	INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	MONTHLY					VARCHAR(4) NULL,

	SALES					DECIMAL(12, 2) NOT NULL,
	EBIT					DECIMAL(12, 2) NOT NULL,
	EBIT_RATE			DECIMAL(12, 2) NULL,
	PBT						DECIMAL(12, 2) NOT NULL,

	PRIMARY KEY ( PLAN_MONTHLY_PAL_SEQ, SEQ)
);

-- 사업계획 > 손익월별계획 - 부서(분기) 합계
CREATE TABLE PLAN_MONTHLY_PAL_BUSINESS_QUARTER_SUM
(
	PLAN_MONTHLY_PAL_SEQ	INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	BUSINESS_QUARTER		VARCHAR(4) NULL,

	SALES					DECIMAL(12, 2) NOT NULL,
	EBIT					DECIMAL(12, 2) NOT NULL,
	EBIT_RATE				DECIMAL(12, 2) NULL,
	PBT						DECIMAL(12, 2) NOT NULL,

	PRIMARY KEY ( PLAN_MONTHLY_PAL_SEQ, SEQ)
);

-- 사업계획 > 손익중기계획
CREATE TABLE PLAN_YEAR_PAL
(
	SEQ					INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,

	YEAR_PAL_YEAR		CHAR(4) NOT NULL,
	ORG_COMPANY_SEQ		INT NOT NULL,
	REGIST_STATUS		INT NOT NULL,

	USER_KEY			VARCHAR(11) NOT NULL,
	EMP_NO				VARCHAR(16) NULL,
	CREATE_DATE			DATETIME NULL

);

-- 사업계획 > 손익중기계획 - 부서별 데이터
CREATE TABLE PLAN_YEAR_PAL_BUSINESS
(
	PLAN_YEAR_PAL_SEQ		INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	ORG_BUSINESS_SEQ		INT NOT NULL,
	YEARLY_YEAR				VARCHAR(4) NOT NULL,

	SALES					DECIMAL(12, 2) NOT NULL,
	EBIT					DECIMAL(12, 2) NOT NULL,
	EBIT_RATE				DECIMAL(12, 2) NULL,
	PBT						DECIMAL(12, 2) NOT NULL,
	PRIMARY KEY ( PLAN_YEAR_PAL_SEQ, SEQ)
);

-- 사업계획 > 손익중기계획 - 부서 합계
CREATE TABLE PLAN_YEAR_PAL_BUSINESS_SUM
(
	PLAN_YEAR_PAL_SEQ	INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	YEARLY_YEAR				VARCHAR(4) NOT NULL,

	SALES					DECIMAL(12, 2) NOT NULL,
	EBIT					DECIMAL(12, 2) NOT NULL,
	EBIT_RATE			DECIMAL(12, 2) NULL,
	PBT						DECIMAL(12, 2) NOT NULL,
	PRIMARY KEY ( PLAN_YEAR_PAL_SEQ, SEQ)
);


-- 사업계획 > 중기BS
CREATE TABLE PLAN_YEAR_BS
(
	SEQ					INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,

	YEAR_BS_YEAR		CHAR(4) NOT NULL,
	ORG_COMPANY_SEQ		INT NOT NULL,
	REGIST_STATUS		INT NOT NULL,

	USER_KEY			VARCHAR(11) NOT NULL,
	EMP_NO				VARCHAR(16) NULL,
	CREATE_DATE			DATETIME NULL
);

-- 사업계획 > 중기BS - B/SHEET
CREATE TABLE PLAN_YEAR_BS_BSHEET
(
	PLAN_YEAR_BS_SEQ		INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	YEARLY_YEAR				VARCHAR(4) NOT NULL,
	MONTHLY					VARCHAR(4) NULL,

	ASSETS					DECIMAL(12, 2) NOT NULL,
	CURRENT_ASSETS			DECIMAL(12, 2) NOT NULL,
	LIABILITIES				DECIMAL(12, 2) NOT NULL,
	CURRENT_LIABILITIES		DECIMAL(12, 2) NOT NULL,
	CAPITAL					DECIMAL(12, 2) NOT NULL,
	CASH					DECIMAL(12, 2) NOT NULL,
	LOAN					DECIMAL(12, 2) NOT NULL,
	LIABILITIES_RATE		DECIMAL(12, 2) NOT NULL,
	CURRENT_RATE			DECIMAL(12, 2) NOT NULL

	PRIMARY KEY (PLAN_YEAR_BS_SEQ, SEQ)
);

-- 사업계획 > 중기BS - ROIC
CREATE TABLE PLAN_YEAR_BS_ROIC
(
	PLAN_YEAR_BS_SEQ		INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	YEARLY_YEAR				VARCHAR(4) NOT NULL,
	MONTHLY					VARCHAR(4) NULL,
	
	AFTER_TAX_OPERATION_PROFIT	DECIMAL(12, 2) NOT NULL,
	PAIN_IN_CAPITAL				DECIMAL(12, 2) NOT NULL,
	ROIC						DECIMAL(12, 2) NOT NULL

	PRIMARY KEY(PLAN_YEAR_BS_SEQ, SEQ)
);

-- 사업계획 > 중기BS - W/CAPITAL
CREATE TABLE PLAN_YEAR_BS_W_CAPITAL
(
	PLAN_YEAR_BS_SEQ		INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	YEARLY_YEAR				VARCHAR(4) NOT NULL,
	ANNUAL_SALES			DECIMAL(12, 2) NOT NULL,
	ANNUAL_SALES_COST		DECIMAL(12, 2) NOT NULL,

	PRIMARY KEY(PLAN_YEAR_BS_SEQ, SEQ)
);

-- 사업계획 > 중기BS - W/CAPITAL 값으로 연산
CREATE TABLE PLAN_YEAR_BS_W_CAPITAL_REG
(
	PLAN_YEAR_BS_SEQ		INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	YEARLY_YEAR				VARCHAR(4) NOT NULL,
	MONTHLY					VARCHAR(4) NULL,

	AR						DECIMAL(12, 2) NOT NULL,
	AR_TO_DAYS				DECIMAL(12, 2) NOT NULL,
	AP						DECIMAL(12, 2) NOT NULL,
	AP_TO_DAYS				DECIMAL(12, 2) NOT NULL,
	INVENTORY				DECIMAL(12, 2) NOT NULL,
	INVENTORY_TO_DAYS		DECIMAL(12, 2) NOT NULL

	PRIMARY KEY(PLAN_YEAR_BS_SEQ, SEQ)
);

-- 사업계획 > 중기BS - 요약
CREATE TABLE PLAN_YEAR_BS_SUMMARY
(
	PLAN_YEAR_BS_SEQ		INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	YEARLY					VARCHAR(4) NOT NULL,
	YEARLY_YEAR				VARCHAR(4) NOT NULL,

	ASSETS					DECIMAL(12, 2) NOT NULL,
	LIABILITIES				DECIMAL(12, 2) NOT NULL,
	CAPITAL					DECIMAL(12, 2) NOT NULL,
	CASH					DECIMAL(12, 2) NOT NULL,
	LOAN					DECIMAL(12, 2) NOT NULL,
	LIABILITIES_RATE		DECIMAL(12, 2) NOT NULL,
	
	AFTER_TAX_OPERATION_PROFIT	DECIMAL(12, 2) NOT NULL,
	PAIN_IN_CAPITAL				DECIMAL(12, 2) NOT NULL,
	ROIC						DECIMAL(12, 2) NOT NULL,

	AR						DECIMAL(12, 2) NOT NULL,
	AR_TO_DAYS				DECIMAL(12, 2) NOT NULL,
	AP						DECIMAL(12, 2) NOT NULL,
	AP_TO_DAYS				DECIMAL(12, 2) NOT NULL,
	INVENTORY				DECIMAL(12, 2) NOT NULL,
	INVENTORY_TO_DAYS		DECIMAL(12, 2) NOT NULL

	PRIMARY KEY(PLAN_YEAR_BS_SEQ, SEQ)
);

-- 사업계획 > 중기CF
CREATE TABLE PLAN_YEAR_CF
(
	SEQ					INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,

	YEAR_BS_YEAR		CHAR(4) NOT NULL,
	ORG_COMPANY_SEQ		INT NOT NULL,
	REGIST_STATUS		INT NOT NULL,

	USER_KEY			VARCHAR(11) NOT NULL,
	EMP_NO				VARCHAR(16) NULL,
	CREATE_DATE			DATETIME NULL
);

-- 사업계획 > 중기CF - 영업활동
CREATE TABLE PLAN_YEAR_CF_SALES
(
	PLAN_YEAR_CF_SEQ		INT NOT NULL,
	SEQ						INT NOT NULL IDENTITY(1, 1),

	YEARLY_YEAR				VARCHAR(4) NOT NULL,
	MONTHLY					VARCHAR(4) NULL,

	OPERATION_PROFIT		DECIMAL(12, 2) NOT NULL,
	DEPRECIATION_COST		DECIMAL(12, 2) NOT NULL,



	PRIMARY KEY(PLAN_YEAR_CF_SEQ, SEQ)
);